query partnershowcase {
  partnerShowcases {
    data {
      id
      attributes {
        slug
        section {
          id
          heading
          image {
            data {
              attributes {
                url
              }
            }
          }
          button {
            label
            href
            classname
            isexternal
          }
        }
      }
    }
  }
}
